<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="10" hostname="DESKTOP-DC5U0BQ" failures="1" tests="1" name="Default test" time="4.011" errors="0" timestamp="2023-07-04T10:23:35 IST">
  <testcase classname="Page_Test.Login_Page_Test" name="TC001_Verify_Login_with_Invalid_credential" time="0.01">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.logging.log4j.Logger.error(String)&amp;quot; because &amp;quot;com.utility.Base_Utility.log&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.logging.log4j.Logger.error(String)" because "com.utility.Base_Utility.log" is null
at com.utility.Base_Utility.msg(Base_Utility.java:403)
at Page_Test.Login_Page_Test.TC001_Verify_Login_with_Invalid_credential(Login_Page_Test.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC001_Verify_Login_with_Invalid_credential -->
  <testcase classname="Page_Test.Login_Page_Test" name="TC008_Verify_Login_with_valid_credential" time="0.0">
    <ignored/>
  </testcase> <!-- TC008_Verify_Login_with_valid_credential -->
  <testcase classname="Page_Test.Login_Page_Test" name="TC009_resend_butn" time="0.0">
    <ignored/>
  </testcase> <!-- TC009_resend_butn -->
  <testcase classname="Page_Test.Login_Page_Test" name="TC006_Privacy_policy" time="0.0">
    <ignored/>
  </testcase> <!-- TC006_Privacy_policy -->
  <testcase classname="Page_Test.Login_Page_Test" name="TC004_max_digit_mobile_number" time="0.0">
    <ignored/>
  </testcase> <!-- TC004_max_digit_mobile_number -->
  <testcase classname="Page_Test.Login_Page_Test" name="TC002_invalidmobileno" time="0.0">
    <ignored/>
  </testcase> <!-- TC002_invalidmobileno -->
  <testcase classname="Page_Test.Login_Page_Test" name="TC003_Verify_Login_with_short_length_of_mobile_number_credential" time="0.0">
    <ignored/>
  </testcase> <!-- TC003_Verify_Login_with_short_length_of_mobile_number_credential -->
  <testcase classname="Page_Test.Login_Page_Test" name="TC005_Terms_of_use_button" time="0.0">
    <ignored/>
  </testcase> <!-- TC005_Terms_of_use_button -->
  <testcase classname="Page_Test.Login_Page_Test" name="TC011_edit_moble" time="0.0">
    <ignored/>
  </testcase> <!-- TC011_edit_moble -->
  <testcase classname="Page_Test.Login_Page_Test" name="TC007_contact_Us" time="0.0">
    <ignored/>
  </testcase> <!-- TC007_contact_Us -->
  <testcase classname="Page_Test.Login_Page_Test" name="TC010_inavalid_OTP" time="0.0">
    <ignored/>
  </testcase> <!-- TC010_inavalid_OTP -->
</testsuite> <!-- Default test -->
